[account] # 优先级高于环境变量
cookie = '' 
# OR
ipbmemberid = ''
ipbpasshash = ''
igneous = ''
sk = '' # 不给的话搜索结果只有英文

[download]
progressBar = true # 下载进度条
threads = 8
retryDepth = 2
useEnvProxy = true # HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof)
domainFronting = false
dir = '' # 留空时使用二进制文件所在目录
